### ISSUE TITLE
can not show realsensecamera in VR

### ISSUE THREAD

**Issue by chendust** [Hao-Starrr/humanoid-arm-retarget#4]
This is a great project, and I want to pay tribute to the developers. I have replicated all the functions of the project on my own robot, except for the real-time display of the RealSense images in the VR application you provided. I streamed the server IP as 192.168.1.106, and I tried to change the IP address in the project to my own IP address (Figure 1), but when I opened the application, it was still blank. I then tried to solve the problem, and I successfully opened the connection in the VR browser (Figure 2), which indicated that it was a non-private connection. I skipped past that and successfully saw the images. Figure 3 shows the debugging error in Xcode, which appears to be an issue with URL parsing. Please tell me how to fix it.
![1](https://github.com/user-attachments/assets/e1c40dc8-a6bd-46eb-9c57-c8768ea3678d)
![2](https://github.com/user-attachments/assets/07901e22-b75c-4951-a8c7-0849eb838d9d)
![3](https://github.com/user-attachments/assets/62f6e9b7-ca5f-4b52-b2e0-4903a42aa7b2)
![image](https://github.com/user-attachments/assets/f9fce20e-194c-47b5-99a0-cd32acdb1638)

**Comment by Hao-Starrr** [comment]
It is probably because https. Apple does not allow WebXR on non-https connections. To test the application locally, we need to create a self-signed certificate and install it on the client. You need a ubuntu machine and a router. Connect the VisionPro and the ubuntu machine to the same router. 
See https://github.com/OpenTeleVision/TeleVision Local streaming part.

**Comment by chendust** [comment]
> It is probably because https. Apple does not allow WebXR on non-https connections. To test the application locally, we need to create a self-signed certificate and install it on the client. You need a ubuntu machine and a router. Connect the VisionPro and the ubuntu machine to the same router. See https://github.com/OpenTeleVision/TeleVision Local streaming part.

Thank you for your reply. I carefully reviewed the process and found two issues. 1. The certificate file uploaded is invalid, and the correct file needs to be generated by running the command "mkcert -CAROOT". 2. Trust the certificate in the universal settings of VR. After fixing these issues, the problem has been resolved. However, I still have a minor issue. The image displayed in VR is a bit small, and is there a way to display it full screen?

**Comment by Hao-Starrr** [comment]
you can resize the webview in visionpro app
```
WebView(url: URL(string: "https://192.168.11.214:8012/?ws=wss://192.168.11.214:8012")!)
                .frame(width: 1500, height: 1200)
```

and can play with these parameters in silverscreen.py

```
ImageBackground(
                                color_image,
                                format="jpeg",
                                quality=40,
                                key="left-image",  # todo: figure out what this means
                                interpolate=True,
                                aspect=1.778,
                                distanceToCamera=2,
                                position=[0, -0.5, -2],
                                rotation=[0, 0, 0],
                            ),
```

**Comment by Hao-Starrr** [comment]
If that doesn't change, Vuer is the library we used in visualization. 
You may find in https://docs.vuer.ai/en/latest/

**Comment by Augston** [comment]
Hi, Chen & Wenhao, I met the same issue that I can't see stream in tracking streamer app but I can see stream in Safari. 
Could this be related to me removing the network extension in Xcode due to not having the Apple Developer Program?
I have installed the CA in Visionpro and succeed in local streaming in Safari. 
I also changed the code with my ip address.
`WebView(url: URL(string: "https://192.168.11.214:8012/?ws=wss://192.168.11.214:8012")!)
                .frame(width: 1500, height: 1200)`
Thanks a lot.
